#!/usr/bin/env bash
# Script that configures a Ubuntu machine through redirecting page commands

apt-get update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
str_replacement="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$str_for_replacement/" /etc/nginx/sites-enabled/default
service nginx restart
