#!/usr/bin/env bash
# Script that configures a Ubuntu machine to have a custom 404 page
# Containing the string Ceci n'est pas une page

apt-get update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
str_replacement="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$str_replacement/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str_replacement/" /etc/nginx/sites-enabled/default
service nginx restart
