#!/usr/bin/env bash
# Script that configures a Ubuntu machine to have
# a custom Nginx response header

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/error1.html
echo -e "Ceci n'est pas une page\n" > /etc/nginx/html/error1.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /error1.html;
    location /error1 {
             root /etc/nginx/html;
             internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
