#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
#   Displays FizzBuzz when the number is a multiple of 3 and 5.
#   Displays Fizz when the number is multiple of 3.
#   Displays Buzz when the number is a multiple of 5.
#   Otherwise, displays the number.

for inum in {1..100}
do 
     if (( inum % 3 == 0 && inum % 5 == 0 ))
     then
       echo "FizzBuzz"
     elif (( inum % 3 == 0 ))
     then
       echo "Fizz"
     elif (( inum % 5 == 0 ))
     then
       echo "Buzz"
     else
       echo "$inum"
     fi
done 
