#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes.
#   display hours from 0 to 12.
#   display minutes from 1 to 59.

ihour=0

while [ $ihour -lt 13 ]
do
  echo "Hour: $ihour"
min=1
  while [ $min -lt 60 ]
  do
    echo "$min"
    ((min++))
  done
  ((ihour++))
done
