#!/usr/bin/env bash
# Bash script that gives you information about the school file.

fschool="school"

if [ -e "$fschool" ]
then
  echo "school file exists"
  if [ -s "$fschool" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "$fschool" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
